[package]
name = "cio-curl-effector-imports"
version = "0.1.1"
edition = "2021"
publish = true
description = "cURL Effector Bindings"
license = "Apache-2.0"
authors = ["composible.io","Fluence Labs"]
repository = "https://github.com/composibleIO/cio-curl-effector"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl-effector-types = { workspace = true }
cio-response-types = { git = "https://github.com/composibleIO/cio-response-types", branch = "main" }
marine-rs-sdk = { workspace = true }
serde = "1.0.198"
